export type AllowanceType =
  | 'housing'
  | 'transportation'
  | 'food'
  | 'supervisory'
  | 'rare'
  | 'gasoline'
  | 'security'
  | 'damage'
  | 'psychology'
  | 'hazard'
  | 'safety'
  | 'excellence'
  | 'education'
